# frozen_string_literal: true

source "https://rubygems.org" do
  gem 'haml'
  gem 'thin'
  gem 'sinatra'
end

source "https://packagecloud.io/avvo/gems" do
  gem 'avvo_kafka', '0.1.4'
end

# gem "rails"
