---
version: 2
jobs:
  build:
    working_directory: ~/kafkamon

    docker:
      - image: avvo/elixir-circleci:1.4.1-3

    environment:
      MIX_ENV: test

    steps:
      - checkout

      - restore_cache:
          key: kafkamon-{{ .Branch }}
          key: kafkamon-master

      - run: mix do deps.get, deps.compile, compile

      - save_cache:
          key: kafkamon-{{ .Branch }}
          key: kafkamon-master
          paths:
            - _build
            - deps

      - run:
          name: Run Tests
          command: mix test

      - store_test_results:
          path: ~/kafkamon/_build/test/lib/

      # all steps after this run in the remote environment
      - type: setup-docker-engine
        reusable: true

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Build docker image and publish container tagged with branch
          command: |
            docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
            bin/build.sh
            docker push avvo/kafkamon:$CIRCLE_BRANCH
      - run:
          name: Publish latest if master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag avvo/kafkamon:release avvo/kafkamon:latest
              docker push avvo/kafkamon:latest
            fi
