FROM avvo/elixir-release:3.5-1

EXPOSE 4000
ENV PORT=4000 MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/sh

ARG SOURCE_COMMIT=0
RUN echo $SOURCE_COMMIT
ENV COMMIT_HASH $SOURCE_COMMIT

WORKDIR /opt/app

ADD kafkamon.tar.gz ./

ENTRYPOINT ["/opt/app/bin/kafkamon"]
CMD ["foreground"]
