---
service_name: kafkamon
stack_name: kafkamon
image: avvo/kafkamon
facing: backend
health_check:
  port: 9292
routing:
  lb_port: 8890
  path: /
  port: 9292
  protocol: http
  subdomain: kafkamon
  websocket: true

cpu_limit: 1000m
cpu_request: 10m
memory_limit: 200Mi
memory_request: 100Mi
