---
service_name: kafkamon
stack_name: kafkamon
image: avvo/kafkamon
facing: backend
health_check:
  port: 4000
  request_line: GET "/options/full_stack_status" "HTTP/1.0"
routing:
  lb_port: 8890
  path: /
  port: 4000
  protocol: http
  subdomain: kafkamon
  websoket: true

cpu_limit: 1000m
cpu_request: 10m
memory_limit: 200Mi
memory_request: 100Mi
