---
service_name: kafkamon
env_on: start
image: avvo/kafkamon
facing: backend
health_check:
  port: 9292
routing:
  path: /
  port: 9292
  protocol: http
  subdomain: kafkamon

cpu_limit: 1000m
cpu_request: 10m
memory_limit: 200Mi
memory_request: 100Mi
