use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :kafkamon, KafkamonWeb.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json",
  check_origin: false,
  server: true

config :logger,
  backends: [
    :console,
  ]

config :logger, level: :debug

config :kafkamon, KafkamonWeb.Endpoint,
  secret_key_base: "+rQn6NCWQZ7qwTlF8qjN5Np+i79HKqUzmD35chCfIf9QJ00iQ9xjVWzldJVCZucQ"
